name: Deploy Java WebApp

on:
  push:
    branches:
      - main   # Runs when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build WAR (for Maven)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Deploy WAR to Server (via SCP/SSH)
      - name: Deploy to Tomcat server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.war"
          target: "/opt/tomcat/webapps/"
